version: '1.0'

services:
  db:
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=inventory
    ports:
      - 5433:5432

volumes:
  pgdata:



